# -*- coding: utf-8 -*-
"""Untitled2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1g1g1gOjd7gIwlyFpuPk8ineIGuEVzN
"""

def calculator():
    #Input values
    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))
    operation = input("Enter the operation (+, -, *, /): ")
    if operation == "+":
        result = num1 + num2
        print(f"{num1} + {num2} = {result}")
    elif operation == "-":
        result = num1 - num2
        print(f"{num1} - {num2} = {result}")
    elif operation == "*":
        result = num1 * num2
        print(f"{num1} * {num2} = {result}")
    elif operation == "/":
        if num2 != 0:
            result = num1 / num2
            print(f"{num1} / {num2} = {result}")
        else:
            print("Error: Division by zero is not allowed.")
    else:
        print("Invalid operation! Please enter one of +, -, *, or /.")

#calling the function
calculator()